conf:
  aws:
    common:
      gitUrl: 'https://github.com/ShaktiAhad/Automation.git'
      branch: 'main'
      jenkinfilePath: 'aws-poc/jenkinfile/Jenkinsfile.main'
      
    awsCodePipeline:
      codeCommitRepo: 'shakti-test-repo'
      cfStack: 's3-bucket-cf'
      codePipeline: 'shakti-test-nodejs'
      region: 'ap-northeast-1'
      inputParams:
        string: 
          releaseVersion:
            defaultValue: 'x.x.x'
            description: 'release version'
            trim: 'true'

          releaseVersion2:
            defaultValue: 'x.x.x2'
            description: 'release version2'
            trim: 'true'

    awsEventRule:
      eventRule: 'test'
      region: 'ap-northeast-1'
      inputParams:
        choice:
          event_rule_status:
            description: 'Change event rule status'
            choices: ['enable', 'disable']