conf:
  aws:
    common:
      gitUrl: 'https://github.com/ShaktiAhad/jenkin-dsl.git'
      branch: 'main'
      cred: 'personal-git-cred'
      
    awsCodePipeline:
      codeCommitRepo: 'shakti-test-repo'
      cfStack:
        name: 's3-bucket-cf'
        parameters: 
          - ParameterKey: 'Environment'
            UsePreviousValue: true
      codePipeline: 'shakti-test-pipeline' # 'shakti-test-nodejs' 
      region: 'ap-northeast-1'
      jenkinfilePath: 'main/jenkinfile_per_pipeline/Jenkinsfile.codePipeline'
      inputParams:
        string: 
          releaseVersion:
            defaultValue: 'x.x.x'
            description: 'release version'
        string: 
          bucket:
            description: 'put bucket name'

    awsEventRule:
      eventRule: 'test'
      region: 'ap-northeast-1'
      jenkinfilePath: 'main/jenkinfile_per_pipeline/Jenkinsfile.eventRule'
      inputParams:
        choice:
          event_rule_status:
            description: 'Change event rule status'
            choices: ['enable', 'disable']