conf:
  google:
    common:
      gitUrl: 'https://github.com/ShaktiAhad/jenkin-dsl.git'
      branch: 'main'
      cred: 'personal-git-cred'
      
    googleCodePipeline:
      codeCommitRepo: 'shakti-test-repo'
      cfStack: 's3-bucket-cf'
      codePipeline: 'shakti-test-pipeline' # 'shakti-test-nodejs'
      eventRule: 'test' 
      region: 'ap-northeast-1'
      inputParams:
        string: 
          releaseVersion:
            defaultValue: 'v0.0.1'
            description: 'release version'

          bucket:
            defaultValue: 'hello-weekend-bucket-v0.0.1'
            description: 'put bucket name'
        
        choice:
          event_rule_status:
            choices: ['skip', 'disable']
            description: 'skip if do not need to change the eventRule status'